### ISSUE TITLE
Test interstitial freezes if tapped

### ISSUE THREAD

**Issue by ESnider** [AppLovin/AppLovin-MAX-Godot#45] opened 2024-12-21 00:12 UTC
### MAX Plugin Version

1.0.3

### Godot Version

4.3

### Device/Platform Info

Pixel 6, android 34 (others)

### Current Behavior

I tapped the 10 second count down test interstitial a few times and the countdown stopped and the ad seemed to just be stuck. I couldn't get it to continue or go away.

### Expected Behavior

Ignore the clicks or do something that doesn't stop the user from getting out of the ad

### How to Reproduce

Load and show a test interstitial in an app in the Android Emulator. Click/tap it a few times as it counts down from 10 seconds. It freezes and won't continue or go away.

![ApplovinTestInterstitial_stuck_on_8_after_clicks](https://github.com/user-attachments/assets/bfed5469-211d-4262-93ce-7036e9743049)

### Reproducible in the demo app?

Not Tested

**Comment by christophercong** [comment] 2024-12-27 04:23
@ESnider I am unable to reproduce this on emulator or device; could you see if you are seeing this issue in the latest plugin release, 1.1.0?

**Comment by christophercong** [comment] 2024-12-28 00:04
This should be fixed/resolved by our backend team.

**Closed as completed by christophercong** 2024-12-28 00:04 UTC
Labels: bug
